# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 15:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sehha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sehha_organization_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sehha_page_create_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
